-- Cursor con parámetro

DECLARE
    CURSOR C1 (IDCAT NUMBER) IS SELECT * FROM PRENDA WHERE IDCAT =IDCAT;
    PRENDA C1%ROWTYPE;
BEGIN
    OPEN C1(3);
    LOOP
        FETCH C1 INTO PRENDA;
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(PRENDA.NOMPRE);
    END LOOP;
    CLOSE C1;
END;


-- Declarar un cursor con la sintaxis FOR UPDATE
DECLARE
CURSOR cur_emps IS
SELECT IDPREN, PRECOMPRE FROM PRENDA
WHERE PRECOMPRE <= 50 FOR UPDATE NOWAIT;
v_emp_rec cur_emps%ROWTYPE;
BEGIN
OPEN cur_emps;
LOOP
FETCH cur_emps INTO v_emp_rec;
EXIT WHEN cur_emps%NOTFOUND;
UPDATE PRENDA
SET PRECOMPRE = v_emp_rec.PRECOMPRE*1.1
WHERE CURRENT OF cur_emps;
END LOOP;
CLOSE cur_emps;
END;




