-- tables
-- Table: CATEGORIA
CREATE TABLE CATEGORIA (
    IDCAT int  NOT NULL,
    NOMCAT varchar2(20)  NOT NULL,
    SETCAT varchar2(20)  NOT NULL,
    CONSTRAINT CATEGORIA_pk PRIMARY KEY (IDCAT)
) ;

-- Table: CLIENTE
CREATE TABLE CLIENTE (
    IDCLI int  NOT NULL,
    NOMCLI varchar2(20)  NOT NULL,
    APECLI varchar2(30)  NOT NULL,
    DNICLI Char(8)  NOT NULL,
    EMACLI varchar2(30)  NOT NULL,
    CELCLI Char(9)  NOT NULL,
    DOMCLI varchar2(30)  NOT NULL,
    ESTCLI Char(1)  DEFAULT 'A',
    CODUBI CHAR(6)  NOT NULL,
    CONSTRAINT CLIENTE_pk PRIMARY KEY (IDCLI)
) ;

-- Table: COMPRA
CREATE TABLE COMPRA (
    IDCOM int  NOT NULL,
    FECCOM date  NOT NULL,
    TIPCOM varchar2(30)  NOT NULL,
    METCOM varchar2(30)  NOT NULL,
    IDPRO int  NOT NULL,
    IDEMP int  NOT NULL,
    CONSTRAINT COMPRA_pk PRIMARY KEY (IDCOM)
) ;

-- Table: COMPRA_DETALLE
CREATE TABLE COMPRA_DETALLE (
    IDCOMDET int  NOT NULL,
    CANCOMDET int  NOT NULL,
    PRECOMPRE decimal(8,2)  NOT NULL,
    IDCOM int  NOT NULL,
    IDPREN int  NOT NULL,
    CONSTRAINT COMPRA_DETALLE_pk PRIMARY KEY (IDCOMDET)
) ;

-- Table: EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMP int  NOT NULL,
    NOMEMP varchar2(20)  NOT NULL,
    APEEMP varchar2(30)  NOT NULL,
    CELEMP Char(9)  NOT NULL,
    DNIEMP Char(8)  NOT NULL,
    EMAEMP varchar2(30)  NOT NULL,
    TIPEMP char(1)  NOT NULL,
    DOMEMP varchar2(30)  NOT NULL,
    ESTEMP Char(1)  DEFAULT 'A',
    CODUBI Char(6)  NOT NULL,
    CONSTRAINT EMPLEADO_pk PRIMARY KEY (IDEMP)
) ;

-- Table: PRENDA
CREATE TABLE PRENDA (
    IDPREN int  NOT NULL,
    NOMPRE varchar2(30)  NOT NULL,
    TALPRE CHAR(5)  NOT NULL,
    PREVENPREN decimal(8,2)  NOT NULL,
    PRECOMPREN decimal(8,2)  NOT NULL,
    STOPRE int  NOT NULL,
    ESTPRE CHAR(1)  DEFAULT 'A',
    COLPRE varchar2(25)  NOT NULL,
    MARPRE varchar2(30)  NOT NULL,
    IDCAT int  NOT NULL,
    IDPRO int  NOT NULL,
    CONSTRAINT PRENDA_pk PRIMARY KEY (IDPREN)
) ;

-- Table: PROVEEDOR
CREATE TABLE PROVEEDOR (
    IDPRO int  NOT NULL,
    RAZSOCPRO varchar2(80)  NOT NULL,
    RUCPRO char(11)  NOT NULL,
    CELPRO char(9)  NOT NULL,
    EMAPRO varchar2(50)  NOT NULL,
    DIRPRO varchar2(80)  NOT NULL,
    CODUBI CHAR(6)  NOT NULL,
    ESTPRO char(1)  DEFAULT 'A',
    CONSTRAINT PROVEEDOR_pk PRIMARY KEY (IDPRO)
) ;

-- Table: UBIGEO
CREATE TABLE UBIGEO (
    CODUBI CHAR(6)  NOT NULL,
    DEPUBI varchar2(30)  NOT NULL,
    PROUBI varchar2(30)  NOT NULL,
    DISUBI varchar2(30)  NOT NULL,
    CONSTRAINT UBIGEO_pk PRIMARY KEY (CODUBI)
) ;

-- Table: VENTA
CREATE TABLE VENTA (
    IDVEN int  NOT NULL,
    FECVEN DATE  NOT NULL,
    ESTVEN CHAR(1)  NOT NULL,
    IDEMP int  NOT NULL,
    IDCLI int  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (IDVEN)
) ;

-- Table: VENTA_DETALLE
CREATE TABLE VENTA_DETALLE (
    IDVENDET int  NOT NULL,
    CANPRE int  NOT NULL,
    IDVEN int  NOT NULL,
    IDPREN int  NOT NULL,
    CONSTRAINT VENTA_DETALLE_pk PRIMARY KEY (IDVENDET)
) ;



--  Create table USUARIO
CREATE TABLE USUARIO (
    IDUSU integer,
    IDEMP integer,
    USUUSU varchar2(10),
    PWDUSU varchar2(15),
    LEVUSU integer ,
    ESTUSU char (1),
    CONSTRAINT USUARIO_pk PRIMARY KEY (IDUSU)
);



-- Crear secuencia categoria INC_CAT
CREATE SEQUENCE INC_CAT
       START WITH 1
       INCREMENT BY 1;

-- Crear disparador de auntoincrementable TRG_INC_CAT
CREATE TRIGGER TRG_INC_CAT
       BEFORE INSERT ON CATEGORIA
       FOR EACH ROW
       BEGIN
           SELECT INC_CAT.NEXTVAL INTO :NEW.IDCAT FROM DUAL;
       END;


-- Crear secuencia cliente INC_CLI
CREATE SEQUENCE INC_CLI
       START WITH 1
       INCREMENT BY 1;

-- Crear disparador de auntoincrementable TRG_INC_CLI
CREATE TRIGGER TRG_INC_CLI
       BEFORE INSERT ON CLIENTE
       FOR EACH ROW
       BEGIN
           SELECT INC_CLI.NEXTVAL INTO :NEW.IDCLI FROM DUAL;
       END;


-- Crear secuencia compra INC_COM
CREATE SEQUENCE INC_COM
       START WITH 1
       INCREMENT BY 1;

-- Crear disparador de auntoincrementable TRG_INC_COM
CREATE TRIGGER TRG_INC_COM
       BEFORE INSERT ON COMPRA
       FOR EACH ROW
       BEGIN
           SELECT INC_COM.NEXTVAL INTO :NEW.IDCOM FROM DUAL;
       END;


-- Crear secuencia compra detalle INC_COMDET
CREATE SEQUENCE INC_COMDET
       START WITH 1
       INCREMENT BY 1;

-- Crear disparador de auntoincrementable TRG_INC_COMDET
CREATE TRIGGER TRG_INC_COMDET
       BEFORE INSERT ON COMPRA_DETALLE
       FOR EACH ROW
       BEGIN
           SELECT INC_COMDET.NEXTVAL INTO :NEW.IDCOMDET FROM DUAL;
       END;


-- Crear secuencia prenda INC_PRE
CREATE SEQUENCE INC_PRE
       START WITH 1
       INCREMENT BY 1;

-- Crear disparador de auntoincrementable TRG_INC_PRE
CREATE TRIGGER TRG_INC_PRE
       BEFORE INSERT ON PRENDA
       FOR EACH ROW
       BEGIN
           SELECT INC_PRE.NEXTVAL INTO :NEW.IDPREN FROM DUAL;
       END;


-- Crear secuencia proveedor INC_PRO
CREATE SEQUENCE INC_PRO
       START WITH 1
       INCREMENT BY 1;

-- Crear disparador de auntoincrementable TRG_INC_PRO
CREATE TRIGGER TRG_INC_PRO
       BEFORE INSERT ON PROVEEDOR
       FOR EACH ROW
       BEGIN
           SELECT INC_PRO.NEXTVAL INTO :NEW.IDPRO FROM DUAL;
       END;
       
       
-- Crear secuencia empleado INC_EMP
CREATE SEQUENCE INC_EMP
       START WITH 1
       INCREMENT BY 1;

-- Crear disparador de auntoincrementable TRG_INC_EMP
CREATE TRIGGER TRG_INC_EMP
       BEFORE INSERT ON EMPLEADO
       FOR EACH ROW
       BEGIN
           SELECT INC_EMP.NEXTVAL INTO :NEW.IDEMP FROM DUAL;
       END;


-- Crear secuencia venta INC_VEN
CREATE SEQUENCE INC_VEN
       START WITH 1
       INCREMENT BY 1;

-- Crear disparador de auntoincrementable TRG_INC_VEN
CREATE TRIGGER TRG_INC_VEN
       BEFORE INSERT ON VENTA
       FOR EACH ROW
       BEGIN
           SELECT INC_VEN.NEXTVAL INTO :NEW.IDVEN FROM DUAL;
       END;


-- Crear secuencia venta_detalle INC_VENDET
CREATE SEQUENCE INC_VENDET
       START WITH 1
       INCREMENT BY 1;

-- Crear disparador de auntoincrementable TRG_INC_VENDET
CREATE TRIGGER TRG_INC_VENDET
       BEFORE INSERT ON VENTA_DETALLE
       FOR EACH ROW
       BEGIN
           SELECT INC_VENDET.NEXTVAL INTO :NEW.IDVENDET FROM DUAL;
       END;


-- Crear secuencia usuario INC_USU
CREATE SEQUENCE INC_USU
       START WITH 1
       INCREMENT BY 1;

-- Crear disparador de auntoincrementable TRG_INC_USU
CREATE TRIGGER TRG_INC_USU
       BEFORE INSERT ON USUARIO
       FOR EACH ROW
       BEGIN
           SELECT INC_USU.NEXTVAL INTO :NEW.IDUSU FROM DUAL;
       END;



-- foreign keys
-- Reference: CLIENTE_UBICACION (table: CLIENTE)
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_UBICACION
    FOREIGN KEY (CODUBI)
    REFERENCES UBIGEO (CODUBI);

-- Reference: COMPRA_DETALLE_COMPRA (table: COMPRA_DETALLE)
ALTER TABLE COMPRA_DETALLE ADD CONSTRAINT COMPRA_DETALLE_COMPRA
    FOREIGN KEY (IDCOM)
    REFERENCES COMPRA (IDCOM);

-- Reference: COMPRA_DETALLE_PRENDA (table: COMPRA_DETALLE)
ALTER TABLE COMPRA_DETALLE ADD CONSTRAINT COMPRA_DETALLE_PRENDA
    FOREIGN KEY (IDPREN)
    REFERENCES PRENDA (IDPREN);

-- Reference: COMPRA_PROVEEDOR (table: COMPRA)
ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_PROVEEDOR
    FOREIGN KEY (IDPRO)
    REFERENCES PROVEEDOR (IDPRO);

-- Reference: COMPRA_VENDEDOR (table: COMPRA)
ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_VENDEDOR
    FOREIGN KEY (IDEMP)
    REFERENCES EMPLEADO (IDEMP);

-- Reference: PRENDA_CATEGORIA (table: PRENDA)
ALTER TABLE PRENDA ADD CONSTRAINT PRENDA_CATEGORIA
    FOREIGN KEY (IDCAT)
    REFERENCES CATEGORIA (IDCAT);

-- Reference: PRENDA_PROVEEDOR (table: PRENDA)
ALTER TABLE PRENDA ADD CONSTRAINT PRENDA_PROVEEDOR
    FOREIGN KEY (IDPRO)
    REFERENCES PROVEEDOR (IDPRO);

-- Reference: PROVEEDOR_UBIGEO (table: PROVEEDOR)
ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_UBIGEO
    FOREIGN KEY (CODUBI)
    REFERENCES UBIGEO (CODUBI);

-- Reference: USUARIO_UBICACION (table: EMPLEADO)
ALTER TABLE EMPLEADO ADD CONSTRAINT USUARIO_UBICACION
    FOREIGN KEY (CODUBI)
    REFERENCES UBIGEO (CODUBI);

-- Reference: VENTA_CLIENTE (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY (IDCLI)
    REFERENCES CLIENTE (IDCLI);

-- Reference: VENTA_DETALLE_PRENDA (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_PRENDA
    FOREIGN KEY (IDPREN)
    REFERENCES PRENDA (IDPREN);

-- Reference: VENTA_DETALLE_VENTA (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_VENTA
    FOREIGN KEY (IDVEN)
    REFERENCES VENTA (IDVEN);

-- Reference: VENTA_USUARIO (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_USUARIO
    FOREIGN KEY (IDEMP)
    REFERENCES EMPLEADO (IDEMP);

-- Relacionar la tabla Empleado a Usuario 
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_EMPLEADO
    FOREIGN KEY (IDEMP) 
    REFERENCES EMPLEADO (IDEMP);



--Insertar UBIGEO
INSERT ALL
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140401', 'Lima', 'Cañete', 'San Vicente')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140402', 'Lima', 'Cañete', 'Calango')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140403', 'Lima', 'Cañete', 'Cerro Azul')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140404', 'Lima', 'Cañete', 'Coayllo')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140405', 'Lima', 'Cañete', 'Chilca')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140406', 'Lima', 'Cañete', 'Imperial')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140407', 'Lima', 'Cañete', 'Lunahuaná')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140408', 'Lima', 'Cañete', 'Mala')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140409', 'Lima', 'Cañete', 'Nuevo Imperial')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140410', 'Lima', 'Cañete', 'Pacarán')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140411', 'Lima', 'Cañete', 'Quilmaná')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140412', 'Lima', 'Cañete', 'San Antonio')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140413', 'Lima', 'Cañete', 'San Luis')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140414', 'Lima', 'Cañete', 'Santa Cruz de Flores')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140415', 'Lima', 'Cañete', 'Zúñiga')
       INTO UBIGEO (CODUBI, DEPUBI, PROUBI, DISUBI) VALUES ('140416', 'Lima', 'Cañete', 'Asia')
       SELECT * FROM DUAL
COMMIT;  

-- Insertar CLIENTE
INSERT ALL
       INTO CLIENTE (NOMCLI, APECLI, DNICLI, EMACLI, CELCLI, DOMCLI, CODUBI) 
       VALUES ('Carmen Olivia', 'Torres Perez', '45781233', 'carment@gmail.com', '929185236', 'Av. Miguel Grau', '140403')
       INTO CLIENTE (NOMCLI, APECLI, DNICLI, EMACLI, CELCLI, DOMCLI, CODUBI) 
       VALUES ('Teodoro Joan', 'Ávila Chumpitaz', '15487922', 'avilaj@gmail.com', '923568741', 'Jr. Quilmaná', '140402')
       INTO CLIENTE (NOMCLI, APECLI, DNICLI, EMACLI, CELCLI, DOMCLI, CODUBI) 
       VALUES ('Oscar Luis', 'Suarez Frances', '15253588', 'oscarsua@gmail.com', '932615478', 'Calle Los Suspiros', '140403')
       INTO CLIENTE (NOMCLI, APECLI, DNICLI, EMACLI, CELCLI, DOMCLI, CODUBI) 
       VALUES ('Eduardo Dani', 'Barrios Palomino', '85213566', 'ebarrios@gmail.com', '932817645', 'Av. Los Girasoles', '140409')       
       INTO CLIENTE (NOMCLI, APECLI, DNICLI, EMACLI, CELCLI, DOMCLI, CODUBI) 
       VALUES ('María Celia', 'Tarazona Mendoza', '15482566', 'mtarazona@gmail.com', '978400123', 'Jr. Cañete', '140407')
       INTO CLIENTE (NOMCLI, APECLI, DNICLI, EMACLI, CELCLI, DOMCLI, CODUBI) 
       VALUES ('Pedro Rodrigo', 'Sánchez Dávila', '15428211', 'psanchez@gmail.com', '941533268', 'Av. Miraflores', '140402')       
       INTO CLIENTE (NOMCLI, APECLI, DNICLI, EMACLI, CELCLI, DOMCLI, CODUBI) 
       VALUES ( 'Aldo Felix', 'Torres Zavala', '47129533','atorres@gmail.com', '958866221', 'Jr. Unión', '140405')
       INTO CLIENTE (NOMCLI, APECLI, DNICLI, EMACLI, CELCLI, DOMCLI, CODUBI) 
       VALUES ('Fiorella Cristina', 'Monteza Alzamora', '48171533', 'fmonteza@gmail.com', '992255441', 'Calle La Esperanza', '140408')
       INTO CLIENTE (NOMCLI, APECLI, DNICLI, EMACLI, CELCLI, DOMCLI, CODUBI) 
       VALUES ('Gloria Tania', 'Linares Rodríguez', '15429866', 'glinares@gmail.com', '954415950', 'Calle Las Begonias', '140403')
       INTO CLIENTE (NOMCLI, APECLI, DNICLI, EMACLI, CELCLI, DOMCLI, CODUBI) 
       VALUES ('Jordana Esperanza', 'Stark Parker', '85251592', 'estark@gmail.com', '901133258', 'Av. Ramón Castilla', '140405')
       SELECT * FROM DUAL
COMMIT;  

-- Insertar EMPLEADO
INSERT ALL
       INTO EMPLEADO (NOMEMP, APEEMP, CELEMP, DNIEMP, EMAEMP,TIPEMP, DOMEMP, CODUBI) 
       VALUES ('Sofia Inés', 'Bolaños Velázquez','910007822','07750457', 'sofia.bolaños@gmail.com', 'A', 'Jiron O Higgins', '140403')
       INTO EMPLEADO (NOMEMP, APEEMP, CELEMP, DNIEMP, EMAEMP,TIPEMP, DOMEMP, CODUBI) 
       VALUES ('Estefany Elisabeth', 'Romero Villa', '915647761', '25735046', 'estefany.romero@gmail.com', 'A', 'Santa Maria Alta', '140409')
       INTO EMPLEADO (NOMEMP, APEEMP, CELEMP, DNIEMP, EMAEMP,TIPEMP, DOMEMP, CODUBI) 
       VALUES ('Juana Edelmira', 'Galván Pascual', '914575236', '21261108', 'juana.galván@gmail.com', 'V', 'Av 28 de Julio', '140406')
       INTO EMPLEADO (NOMEMP, APEEMP, CELEMP, DNIEMP, EMAEMP,TIPEMP, DOMEMP, CODUBI)  
       VALUES ('Luciano Dafne', 'Rivera Campo', '915908420', '46967914', 'luciano.rivera@gmail.com', 'V', 'Av 2 de Mayo', '140406')       
       INTO EMPLEADO (NOMEMP, APEEMP, CELEMP, DNIEMP, EMAEMP,TIPEMP, DOMEMP, CODUBI) 
       VALUES ('Angela Estrella', 'Rodriguez León', '921367745', '07756532', 'angela.rodriguez@gmail.com', 'V', 'Cerro Libre', '140409')
       INTO EMPLEADO (NOMEMP, APEEMP, CELEMP, DNIEMP, EMAEMP,TIPEMP, DOMEMP, CODUBI) 
       VALUES ('Rocio Jessica', 'Sotelo Lara', '916156023', '45055499', 'rocio.sotelo@gmail.com', 'V', 'Av Ayacucho', '140406')       
       INTO EMPLEADO (NOMEMP, APEEMP, CELEMP, DNIEMP, EMAEMP,TIPEMP, DOMEMP, CODUBI) 
       VALUES ('Felix Renato', 'Cruz Santiago', '913881305', '06224656', 'felix.cruz@gmail.com', 'V', 'Cementerio', '140406')
       INTO EMPLEADO (NOMEMP, APEEMP, CELEMP, DNIEMP, EMAEMP,TIPEMP, DOMEMP, CODUBI) 
       VALUES ('Paul Donato', 'Ramos Roda', '925829547', '15448909', 'paul.ramos@gmail.com', 'V', 'Caltopilla', '140407')
       INTO EMPLEADO (NOMEMP, APEEMP, CELEMP, DNIEMP, EMAEMP,TIPEMP, DOMEMP, CODUBI) 
       VALUES ('Emma Rosario', 'Redondo Abascal', '923547549', '16458936', 'emma.redondo@gmail.com', 'V', 'Calle Las Begonias', '140403')
       INTO EMPLEADO (NOMEMP, APEEMP, CELEMP, DNIEMP, EMAEMP,TIPEMP, DOMEMP, CODUBI) 
       VALUES ('Bruno Julio', 'Robles Saavedra', '917420895', '12569827', 'bruno.robles@gmail.com', 'V', 'Av. Ramón Castilla', '140405')
       SELECT * FROM DUAL
COMMIT;  

-- Insertar CATEGORIA
INSERT ALL
       INTO CATEGORIA (NOMCAT, SETCAT)
       VALUES ('Formal','Mujeres')
       INTO CATEGORIA (NOMCAT, SETCAT)
       VALUES ('Casual','Mujeres')
       INTO CATEGORIA (NOMCAT, SETCAT)
       VALUES ('Casual','Hombre')
       INTO CATEGORIA (NOMCAT, SETCAT)
       VALUES ('Formal','Hombre')
       SELECT * FROM DUAL
COMMIT;

-- Insertar PROVEEDOR
INSERT ALL
       INTO PROVEEDOR (RAZSOCPRO, RUCPRO, CELPRO, EMAPRO, DIRPRO, CODUBI)
       VALUES ('Soriano', '70734234242','925446536','pedroz@gmail.com','Av Los Girasoles','140401')
       INTO PROVEEDOR (RAZSOCPRO, RUCPRO, CELPRO, EMAPRO, DIRPRO, CODUBI)
       VALUES ('JuanC', '11434454981','976493512','ignacioc@gmail.com','Av Ayacucho', '140406' )
       INTO PROVEEDOR (RAZSOCPRO, RUCPRO, CELPRO, EMAPRO, DIRPRO, CODUBI)
       VALUES ('Ginkgo','71834243242','949046563','ginkgo2@gmail.com','Av. Ramón Castilla', '140405')
       INTO PROVEEDOR (RAZSOCPRO, RUCPRO, CELPRO, EMAPRO, DIRPRO, CODUBI)
       VALUES ('Inca Clothing', '13734454067','971493510','incaclothing@gmail.com','Santa Maria Alta', '140409')
       INTO PROVEEDOR (RAZSOCPRO, RUCPRO, CELPRO, EMAPRO, DIRPRO, CODUBI)
       VALUES ('Garne', '13876243290','913044769','garneriv@gmail.com','Calle Las Begonias', '140403')
       SELECT * FROM DUAL
COMMIT; 

-- Insertar PRENDA
INSERT ALL
       INTO PRENDA (NOMPRE, TALPRE, PREVENPREN, PRECOMPREN, STOPRE, COLPRE, MARPRE, IDCAT, IDPRO) 
       VALUES ('Polera', 'S', 115.00, 100.00, 5, 'Rojo','Gisuck',1,1)
       INTO PRENDA (NOMPRE, TALPRE, PREVENPREN, PRECOMPREN, STOPRE, COLPRE, MARPRE, IDCAT, IDPRO) 
       VALUES ('Polo', 'S', 35.00, 20.00, 40, 'Negro', 'Adidas', 1, 2)
       INTO PRENDA (NOMPRE, TALPRE, PREVENPREN, PRECOMPREN, STOPRE, COLPRE, MARPRE, IDCAT, IDPRO)  
       VALUES ('Jogger', 'S', 45.00, 30.00, 20, 'Beige', 'Alpha fit', 2, 1)
       INTO PRENDA (NOMPRE, TALPRE, PREVENPREN, PRECOMPREN, STOPRE, COLPRE, MARPRE, IDCAT, IDPRO) 
       VALUES ('Jeans', 'S', 55.00, 40.00, 50, 'Blanco', 'Frame', 1, 2)       
       INTO PRENDA (NOMPRE, TALPRE, PREVENPREN, PRECOMPREN, STOPRE, COLPRE, MARPRE, IDCAT, IDPRO)  
       VALUES ('Jeans', 'M', 55.00, 40.00, 60, 'Negro', 'Paige', 1, 1)
       INTO PRENDA (NOMPRE, TALPRE, PREVENPREN, PRECOMPREN, STOPRE, COLPRE, MARPRE, IDCAT, IDPRO)  
       VALUES ('Camisa', 'L', 43.00, 28.00, 24, 'Morado', 'Osklen', 4, 1)       
       SELECT * FROM DUAL
COMMIT;   


-- Insertar VENTA
INSERT ALL
       INTO VENTA (FECVEN, ESTVEN, IDEMP, IDCLI, TOTVEN)
       VALUES ('12-06-2022', 'A', 4, 1, 205)
       INTO VENTA (FECVEN, ESTVEN, IDEMP, IDCLI, TOTVEN)
       VALUES ('12-06-2022', 'A', 6, 1, 90)
       INTO VENTA (FECVEN, ESTVEN, IDEMP, IDCLI, TOTVEN)
       VALUES ('20-07-2022', 'A', 3, 4, 275)
       INTO VENTA (FECVEN, ESTVEN, IDEMP, IDCLI, TOTVEN)
       VALUES ('20-07-2022', 'A', 3, 2, 200)
       SELECT * FROM DUAL
COMMIT;

-- Insertar VENTA_DETALLE
INSERT ALL
       INTO VENTA_DETALLE (CANPRE, IDVEN, IDPREN, SUBVENDET)
       VALUES (1,1,1,115)
       INTO VENTA_DETALLE (CANPRE, IDVEN, IDPREN, SUBVENDET)
       VALUES (2,1,3,90)
       INTO VENTA_DETALLE (CANPRE, IDVEN, IDPREN, SUBVENDET)
       VALUES (2,2,3,90)
       INTO VENTA_DETALLE (CANPRE, IDVEN, IDPREN, SUBVENDET)
       VALUES (5,3,4,275)
       INTO VENTA_DETALLE (CANPRE, IDVEN, IDPREN, SUBVENDET)
       VALUES (1,4,2,35)
       INTO VENTA_DETALLE (CANPRE, IDVEN, IDPREN, SUBVENDET)
       VALUES (3,4,5,165)
       SELECT * FROM DUAL
COMMIT;

-- Insertar COMPRA
INSERT ALL
       INTO COMPRA (FECCOM, TIPCOM, METCOM, IDPRO, IDEMP)
       VALUES ('11-07-2022', 'P', 'Yape', 1, 1)
       INTO COMPRA (FECCOM, TIPCOM, METCOM, IDPRO, IDEMP)
       VALUES ('20-08-2022', 'P', 'Yape', 3, 2)
       INTO COMPRA (FECCOM, TIPCOM, METCOM, IDPRO, IDEMP)
       VALUES ('21-08-2022', 'P', 'Yape', 2, 1)
       SELECT * FROM DUAL
COMMIT;

-- Insertar COMPRA_DETALLE
INSERT ALL
       INTO COMPRA_DETALLE (CANCOMDET, IDCOM, IDPREN, PRECOMPRE)
       VALUES (1, 1, 2, 20.00)
       INTO COMPRA_DETALLE (CANCOMDET, IDCOM, IDPREN, PRECOMPRE)
       VALUES (3, 2, 4, 40.00)
       INTO COMPRA_DETALLE (CANCOMDET, IDCOM, IDPREN, PRECOMPRE)
       VALUES (2, 3, 6, 28.00)
       INTO COMPRA_DETALLE (CANCOMDET, IDCOM, IDPREN, PRECOMPRE)
       VALUES (2, 3, 2, 20.00)
       SELECT * FROM DUAL
COMMIT;



--vista para Cliente
CREATE VIEW vCliente
AS
SELECT
     C.IDCLI AS IDCLI, 
     C.NOMCLI AS NOMCLI,
     C.APECLI AS APECLI,
	 C.DNICLI AS DNICLI,
	 C.EMACLI AS EMACLI, 
     C.CELCLI AS CELCLI,
	 C.DOMCLI AS DOMCLI,
     U.CODUBI AS CODUBI,
	 U.DISUBI AS DISUBI, 
	 U.PROUBI AS PROUBI,
	 U.DEPUBI AS DEPUBI,
	 C.ESTCLI AS ESTCLI,
	 ROW_NUMBER() OVER (ORDER BY C.IDCLI DESC) AS ORDEN
FROM 
     CLIENTE C
 INNER JOIN UBIGEO U ON
	 C.CODUBI = U.CODUBI;

--vista para vendedor
CREATE VIEW vEmpleado
AS
SELECT
     E.IDEMP AS IDEMP, 
     E.NOMEMP AS NOMEMP,
     E.APEEMP AS APEEMP,
	 E.CELEMP AS CELEMP,
	 E.DNIEMP AS DNIEMP,
	 E.EMAEMP AS EMAEMP, 
     E.TIPEMP AS TIPEMP, 
     E.DOMEMP AS DOMEMP,
	 E.CODUBI AS CODUBI,
     U.DISUBI AS DISUBI,
	 U.PROUBI AS PROUBI,
	 U.DEPUBI AS DEPUBI,
	 E.ESTEMP AS ESTEMP,
	 ROW_NUMBER() OVER (ORDER BY E.IDEMP DESC) AS ORDEN
FROM 
     EMPLEADO E
 INNER JOIN UBIGEO U ON
	 E.CODUBI = U.CODUBI;

--vista para Proveedor
CREATE VIEW vProveedor
AS
SELECT
     P.IDPRO AS IDPRO,
     P.RUCPRO AS RUCPRO,
	 P.RAZSOCPRO AS RAZSOCPRO,  
     P.CELPRO AS CELPRO, 
     P.EMAPRO AS EMAPRO,
	 P.DIRPRO AS DIRPRO,
     U.CODUBI AS CODUBI,
	 U.DISUBI AS DISUBI, 
	 U.PROUBI AS PROUBI,
	 U.DEPUBI AS DEPUBI,
	 P.ESTPRO AS ESTPRO,
	 ROW_NUMBER() OVER (ORDER BY P.IDPRO DESC) AS ORDEN
FROM 
     PROVEEDOR P
 INNER JOIN UBIGEO U ON
	 P.CODUBI = U.CODUBI;
     
--vista para prenda
CREATE VIEW vPrenda
AS
SELECT 
	P.IDPREN AS IDPREN,
	P.NOMPRE AS NOMPRE,
	P.TALPRE AS TALPRE,
	P.PREVENPREN AS PREVENPREN,
    P.PRECOMPREN AS PRECOMPREN,
	P.STOPRE AS STOPRE,
	P.COLPRE AS COLPRE,
	P.MARPRE AS MARPRE,
	C.IDCAT AS IDCAT,
	C.NOMCAT AS NOMCAT, 
	C.SETCAT AS SETCAT,
	PR.IDPRO AS IDPRO,
	PR.RUCPRO AS RUCPRO,
	PR.RAZSOCPRO AS RAZSOCPRO,
	P.ESTPRE AS ESTPRE,
	ROW_NUMBER() OVER (ORDER BY P.IDPREN DESC) AS ORDEN
FROM PRENDA P 
INNER JOIN CATEGORIA C
	ON P.IDCAT = C.IDCAT
INNER JOIN PROVEEDOR PR
	ON P.IDPRO = PR.IDPRO;

-- Vista usada en Venta
CREATE VIEW vVenta
AS
SELECT
    V.IDVEN AS IDVEN,
    C.DNICLI AS DNICLI,
	C.IDCLI AS IDCLI,
	UPPER(C.APECLI || ' ' || C.NOMCLI) AS NOMCLI,
    V.FECVEN AS FECVEN,
    V.TOTVEN AS TOTVEN
FROM VENTA V
    INNER JOIN CLIENTE C
    ON V.IDCLI = C.IDCLI;


-- Vista para COMPRA
CREATE VIEW vCOMPRA
AS
SELECT
    C.IDCOM AS IDCOM,
    C.FECCOM AS FECCOM,
    P.IDPRO AS IDPRO,
    P.RUCPRO AS RUCPRO,
	P.RAZSOCPRO AS RAZSOCPRO,
    C.TOTCOM AS TOTCOM
FROM COMPRA C
    INNER JOIN PROVEEDOR P
    ON C.IDPRO = P.IDPRO;



-- Vista reporte de venta
CREATE VIEW vReporte
AS
SELECT 
	V.IDVEN,
	V.FECVEN,
	(UPPER(C.APECLI) + ', ' + C.NOMCLI) AS CLIENTE,
	C.DNICLI AS DNI_CLIENTE,
	(U.DISUBI + ' | ' + U.PROUBI + ' | ' + U.DEPUBI) AS UBICACION,
	VD.CANPRE,
	P.NOMPRE AS PRENDA,
	P.PREVENPREN AS PRECIO,
	(P.PREVENPREN * VD.CANPRE) AS SUBTOTAL
FROM VENTA  V INNER JOIN CLIENTE C
	ON V.IDCLI = C.IDCLI
	INNER JOIN UBIGEO U
	ON C.CODUBI = U.CODUBI
	INNER JOIN VENTA_DETALLE VD
	ON V.IDVEN = VD.IDVEN
	INNER JOIN PRENDA P
	ON VD.IDPREN = P.IDPREN;
    
    
CREATE VIEW vRoLUsuario
AS
SELECT
     U.USUUSU AS USUUSU,
     U.PWDUSU AS PWDUSU,
     E.TIPEMP AS TIPEMP
FROM 
     USUARIO U
	 INNER JOIN EMPLEADO E ON
	 U.IDEMP = E.IDEMP;
    
    

---CREACIÓN DE TRIGGERS
--Stock EN VENTA
CREATE OR REPLACE TRIGGER REDUCIR_STOCK
AFTER INSERT ON VENTA_DETALLE FOR EACH ROW 
DECLARE
BEGIN
    UPDATE PRENDA P
    SET STOPRE = P.STOPRE - VD.CANVENDET
    WHERE
    IDPRE = IDPRE AND IDVENDET = (SELECT MAX(IDVENDET) FROM VENTA_DETALLE)VD
    WHERE P.IDPRE = VD.IDPRE;
END;
/


-- Vista para SUMAR STOCK EN COMPRA
CREATE OR REPLACE TRIGGER AUMENTAR_STOCK
AFTER INSERT ON COMPRA_DETALLE FOR EACH ROW 
DECLARE
BEGIN
    UPDATE PRENDA P
    SET STOPRE = P.STOPRE + CD.CANCOMDET
    WHERE
    IDPRE = IDPRE AND IDCOMDET = (SELECT MAX(IDCOMDET) FROM COMPRA_DETALLE)) CD
    WHERE P.IDPRO = CD.IDPRE;
END;

--Procedure Cliente


CREATE PROCEDURE spInertCliente
(
		@IDCLI int ,
        @NOMCLI varchar(50),
		@APECLI varchar(50),
		@DNICLI char(8),
        @EMACLI varchar(50),      
        @CELCLI char(9),
        @DOMCLI varchar(50),@ESTCLI char(1)
        
        @CODUBI char(6),
		
  )
 AS 
 BEGIN 
SET NOCOUNT ON 
INSERT INTO  CLIENTE 
(IDCLI, NOMCLI, APECLI, DNICLI, EMACLI,  CELCLI, DOMCL, ESTCLII, CODUBI)
VALUES 
(@IDCLI ,@NOMCLI ,@APECLI ,@DNICLI, @EMACLI ,@CELCLI, @DOMCLI, @ESTCLI, @CODUBI)
SELECT * FROM CLIENTE
WHERE IDCLI = @IDCLI
END 
GO 

select * from usuario;
select USUUSU, PWDUSU, LEVUSU from USUARIO where USUUSU=Estefany and PWDUSU=Tefyromero;